version: 2

sources:
  - name: erp_northwind
    description: Fonte do SAP de vendas
    schema: erp_northwind
    tables:
      - name: products  # enabled
        description: Tabela de produtos
      - name: suppliers  # enabled
        description: Tabela de fornecedores
      - name: categories  # enabled
        description: Tabela de categorias de produtos
        columns:
          - name: category_id
            description: chave primária da tabela de categorias de produtos
            tests:
              - unique
              - not_null
              - dbt_expectations.expect_column_values_to_not_be_null:
                  row_condition: "category_id is not null" # (Optional)
      - name: customers
      - name: orders
        description: Uma linha por pedido. Inclui pedidos cancelados e deletados
        columns:
          - name: order_id
            tests:
              - unique 
              - not_null
      - name: order_details
        description: Uma linha por produto do pedido. 
